export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Mo.Salah",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpg",
    username: "M.Ghoraba",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpg",
    username: "A.Naouf",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpg",
    username: "M.Ali",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpg",
    username: "K.Hamed",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpg",
    username: "H.Khalifa",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpg",
    username: "S.Tamer",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpg",
    username: "Y.Mazin",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpg",
    username: "W.Yassin",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpg",
    username: "M.Reda",
  },
];

export const Posts = [
  {
    id: 1,
    desc:" Lamin Yamal is a goledn boy.",
    photo: "assets/post/1.jpg",
    date: "5 hours ago",
    userId: 1,
    like: 10000,
    comment: 1119,
  },
  {
    id: 2,
    desc:" Officailly, became software engineer",
    photo: "assets/post/2.jpg",
    date: "17 July 2023",
    userId: 2,
    like: 100000000000,
    comment: 2555555,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 17,
    comment: 13,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Far Cry 4.",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
